#include <iostream>
#include <string>

#ifndef Maple_string_H
#define Maple_string_H

using namespace std;

string Job[], Item[], other_Case[];

Job[] = {"Hero", // 모험가
        "Darknight",
        "paladin",
        "Bowmaster",
		    "Sniper",
        "Pathfinder",
        "ArchmageTc",
        "ArchmageFb",
		    "Bishop",
        "Nightlord",
        "Shadower",
        "Dualblade",
		    "Captain",
        "Viper",
        "Cannon_Shooter",
        "SoulMaster", // 시그너스
		    "Windbreaker",
        "Flamewizerd",
        "Nightwalker",
        "Striker",
		    "Blaster", // 레지스탕스
        "Micheal",
        "Wildhunter",
        "Battlemage",
		    "Mechanic",
        "Xenon",
        "Demonavenger", // 데몬
        "Demonslayer",
		    "Aran", // 영웅
        "Mercedes",
        "Evan",
        "Luminous",
		    "Phamtom",
        "Eunoul",
        "Kaiser", // 노바
        "Kain",
		    "Cadena",
        "Anglicbuster",
        "Adele", // 레프
        "Ilium",
		    "Ark",
        "Hoyoung", // 혼밥
        "Zero",
        "Kinesis"
        };

other_Case[] = {"Warriors", "Bowmen", "Magicians", "Thieves", "Porates"};


#define max_damage = 150000000000

#endif